### ISSUE TITLE
중복확인 in 내 정보 수정

### ISSUE THREAD

**Issue by snorlexK** [me9min/HOSEO-2A-2-Plare#3]
jsp UI
- 중복확인 버튼을 닉네임변경으로 변경
- 최근 닉변일 표시 in readonly

버튼 클릭 시 js
- 닉네임 변경 가능한 날짜인지 검사

js > submit() > jsp 및 java
- 새 창에서 닉네임 입력 및 중복확인 절차 진행

**Comment by snorlexK** [comment]
최근 닉변일 표시 in readonly

**Comment by me9min** [comment]
js > submit() > jsp 및 java
- 새 창에서 닉네임 입력 및 중복확인 절차 진행 (현재 JS로 구현, 실제DB체크함)

**Comment by me9min** [comment]
https://github.com/me9min/HOSEO-2A-2-Plare/commit/2ce3c5965fb36dcb9a67f05c5b8b55b2cc21b7c6
